# Site settings
title: First a programmer, Then a web coder
email: isi_liuxu@yeah.net
description: > # this means to ignore newlines until "baseurl:"
  migrated from http://blog.csdn.net/vctisildur
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://victorisildur.github.io" # the base hostname & protocol for your site
github_username: victorisildur 

# Build settings
markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: ["tables", "no_intra_emphasis", "fenced_code_blocks", "autolink"]